export async function getMyExecutedTransactions() {
  return (getExecutedTransactions()).slice(0, 3)
}

export async function getExecutedTransaction(id: string) {
  return (getExecutedTransactions()).find((transaction) => transaction.cid === id)!
}

export function getExecutedTransactions() {
  return [
    {
      cid: "12345",
      block: "1000004",
      owner: "0x1234...5678",
      operation: "Contract call",
      url: "/compose/12345",
      status: "Confirmed",
      imgUrl: "ideal/original-original.png",
      fee: "1.0",
    },
    {
      cid: "12346",
      block: "1000003",
      owner: "0x1234...5678",
      operation: "Extrinsic call",
      url: "/compose/12346",
      status: "Failed",
      imgUrl: "ideal/original-original.png",
      fee: "1.0",
    },
    {
      cid: "12347",
      block: "1000002",
      owner: "0x1234...5678",
      operation: "Contract call",
      url: "/compose/12347",
      status: "Confirmed",
      imgUrl: "ideal/original-original.png",
      fee: "1.0",
    },
    {
      cid: "12348",
      block: "1000001",
      owner: "0x1234...5678",
      operation: "Balance Transfer",
      url: "/compose/12348",
      status: "Failed",
      imgUrl: "ideal/original-original.png",
      fee: "1.0",
    },
    {
      cid: "12349",
      block: "1000000",
      owner: "0x1234...5678",
      operation: "Contract call",
      url: "/compose/12349",
      status: "Confirmed",
      imgUrl: "ideal/original-original.png",
      fee: "1.0",
    },
  ]
}

export function getScheduledTransactions() {
  return [
    {
      cid: "22345",
      block: "1000004",
      deadLineBlock: "1000100",
      owner: "0x1234...5678",
      operation: "Contract call",
      url: "/compose/22345",
      status: "Scheduled",
      imgUrl: "ideal/original-original.png",
      fee: "1.0",
    },
    {
      cid: "22346",
      block: "1000003",
      deadLineBlock: "1000200",
      owner: "0x1234...5678",
      operation: "Extrinsic call",
      url: "/compose/22346",
      status: "Scheduled",
      imgUrl: "ideal/original-original.png",
      fee: "1.0",
    },
    {
      cid: "22347",
      block: "1000002",
      deadLineBlock: "1000100",
      owner: "0x1234...5678",
      operation: "Contract call",
      url: "/compose/22347",
      status: "Scheduled",
      imgUrl: "ideal/original-original.png",
      fee: "1.0",
    },
    {
      cid: "22348",
      block: "1000001",
      deadLineBlock: "1001000",
      owner: "0x1234...5678",
      operation: "Balance Transfer",
      url: "/compose/22348",
      status: "Scheduled",
      imgUrl: "ideal/original-original.png",
      fee: "1.0",
    },
    {
      cid: "22349",
      block: "1000000",
      deadLineBlock: "1002000",
      owner: "0x1234...5678",
      operation: "Contract call",
      url: "/compose/22349",
      status: "Scheduled",
      imgUrl: "ideal/original-original.png",
      fee: "1.0",
    },
  ]
}

export function getGeneratedRandomness() {
  return [
    {
      cid: "32345",
      block: "1000004",
      randomness: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      status: "Generated",
    },
    {
      cid: "32346",
      block: "1000004",
      randomness: "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
      status: "Generated",
    },
    {
      cid: "32347",
      block: "1000003",
      randomness: "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ",
      status: "Generated",
    },
  ]
}

export function getCountries() {
  return [
    {
      name: 'Canada',
      code: 'CA',
      flagUrl: '/flags/ca.svg',
      regions: [
        'Alberta',
        'British Columbia',
        'Manitoba',
        'New Brunswick',
        'Newfoundland and Labrador',
        'Northwest Territories',
        'Nova Scotia',
        'Nunavut',
        'Ontario',
        'Prince Edward Island',
        'Quebec',
        'Saskatchewan',
        'Yukon',
      ],
    },
    {
      name: 'Mexico',
      code: 'MX',
      flagUrl: '/flags/mx.svg',
      regions: [
        'Aguascalientes',
        'Baja California',
        'Baja California Sur',
        'Campeche',
        'Chiapas',
        'Chihuahua',
        'Ciudad de Mexico',
        'Coahuila',
        'Colima',
        'Durango',
        'Guanajuato',
        'Guerrero',
        'Hidalgo',
        'Jalisco',
        'Mexico State',
        'Michoacán',
        'Morelos',
        'Nayarit',
        'Nuevo León',
        'Oaxaca',
        'Puebla',
        'Querétaro',
        'Quintana Roo',
        'San Luis Potosí',
        'Sinaloa',
        'Sonora',
        'Tabasco',
        'Tamaulipas',
        'Tlaxcala',
        'Veracruz',
        'Yucatán',
        'Zacatecas',
      ],
    },
    {
      name: 'United States',
      code: 'US',
      flagUrl: '/flags/us.svg',
      regions: [
        'Alabama',
        'Alaska',
        'American Samoa',
        'Arizona',
        'Arkansas',
        'California',
        'Colorado',
        'Connecticut',
        'Delaware',
        'Washington DC',
        'Micronesia',
        'Florida',
        'Georgia',
        'Guam',
        'Hawaii',
        'Idaho',
        'Illinois',
        'Indiana',
        'Iowa',
        'Kansas',
        'Kentucky',
        'Louisiana',
        'Maine',
        'Marshall Islands',
        'Maryland',
        'Massachusetts',
        'Michigan',
        'Minnesota',
        'Mississippi',
        'Missouri',
        'Montana',
        'Nebraska',
        'Nevada',
        'New Hampshire',
        'New Jersey',
        'New Mexico',
        'New York',
        'North Carolina',
        'North Dakota',
        'Northern Mariana Islands',
        'Ohio',
        'Oklahoma',
        'Oregon',
        'Palau',
        'Pennsylvania',
        'Puerto Rico',
        'Rhode Island',
        'South Carolina',
        'South Dakota',
        'Tennessee',
        'Texas',
        'Utah',
        'Vermont',
        'U.S. Virgin Islands',
        'Virginia',
        'Washington',
        'West Virginia',
        'Wisconsin',
        'Wyoming',
        'Armed Forces Americas',
        'Armed Forces Europe',
        'Armed Forces Pacific',
      ],
    },
  ]
}
